### ISSUE TITLE
Phone permission

### ISSUE THREAD

**Issue by Klejdi-Bozho** [Bnyro/ConnectYou#106]
### Describe your suggested feature

Hello! This was requested in #94 and rejected due to the fact that it would require phone permission. Implementing the ability to call immidiently when hitting a number would be a huge time saver. This feature is necessary because all other contacts apps have it. If not can you please explain why not? Thank you! 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In my opinion every app should only require the permissions it really needs. I've initially created the app since other contact apps I've found used either weird permissions or looked really ugly. The permission to call someone directly is probably not self-explaining for new users since it's a contacts and not a dialer app. It's only one additional click to call someone without the app having the permisison, so I don't really see a drastic need for it here.

**Comment by harishkumarankr2004** [comment]
> Yes you are right, I use GrapheneOS, but as for one extra click, that might not be much of an issue for the average user, in my work i have to make many calls a day, and all the extra clicks could add up. 

Maybe you should try some other apps like Google Contacts/Simple Contacts of you want that kind of experience.
But I think this app is meant to have minimal permission and hence won't be implemented.
