### ISSUE TITLE
Search icon replacing Search Bar

### ISSUE THREAD

**Issue by harishkumarankr2004** [Bnyro/ConnectYou#156]
### Describe your suggested feature

Remove the existing search bar and implement a search icon.
Search bar has 
1) no use
2) takes so much space
3) Looks ugly
Search icons are
1)accessible the same way
2)take very less space
3) Looks beautiful😍 

### Other details

I would also like the App's name to be mentioned in place of the removed search bar.
With the arrival of material you, all apps have extremely similar UI/UX and also theming.
This causes confusion to users which app is which (not big of a deal though).
Adding the app name on the top bar would also help resolve this and also looks good.
Also I think it's a personal preference to whether we add this or not.
Take a look at the GrapheneOS's Apps application's top bar.

![Screenshot_20230508-001909~2](https://user-images.githubusercontent.com/132816149/236697370-a1204a96-9397-44a0-aca2-36ab8bab20d1.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The current search bar has the advantage of being faster to access and always visible, which is reasonable as the search feature is probably one of the most used ones in a contacts app.
I don't really see the point of always needing to add the app name to the left: either you use the app and know its name or you don't.
And if all apps "look" similar (which was your argument), having a search bar that looks different than in other apps makes Connect You more unique and users can't mix it up with others :rocket:

**Comment by Bnyro** [comment]
That's exactly what I won't do. 
I built all the different apps to look and feel different, in order to make it fun to work on them. 
If all looked the same and used the same components, it would start getting boring really fast.
Also, I don't have any plans on redesigning and improving them a lot, I mostly will fix issues and add smaller features but all in all they're pretty much finalized.

**Comment by harish-kumaran** [comment]
> That's exactly what I won't do. 
> I built all the different apps to look and feel different, in order to make it fun to work on them. 
> If all looked the same and used the same components, it would start getting boring really fast.
> Also, I don't have any plans on redesigning and improving them a lot, I mostly will fix issues and add smaller features but all in all they're pretty much finalized.

What is "that" you won't do make your apps not look similar but follow similar design philosophies? I think the opposite.

If you made the app's different for your fun then that's fine but, remember real people use these apps in real lives so it's not just a toy/hobby project. If it is, then something is going wrong.

If you are saying that the design is finalised, then in my point of view all of these apps look horrible from UI/UX perspective and also functionality wise, very few attention to detail and too many bugs.

This is just my opinion and I got this the moment I saw ur ConnectYou app and subsequently those recorder, clock I just got sure these aren't real world apps meant for doing real stuff efficiently.

NOTE: Don't get triggered by this, it's just what I think after being for months aka my opinions but from heart without any hatred towards you[although a little ;)]

**Comment by harish-kumaran** [comment]
> I've been working with Android for more than a year now and my motivation to develop with it has decreased drastically, nowadays I prefer developing other things that are not related to Android, just because I want to do something fun in my free time which Android development kinda sucks at, at least after a certain time.

I can see that that's why I kept on asking.
Thanks for confirming. I knew coz these apps didn't look what the way I saw other suite of apps.
Let's hope another developer forks these projects and develops it or wait lemme develop it. Oh you need to know programming for that, nvm I'll try to learn from now maybe after 5-6 months I'll be good. Let's see.

**Comment by Bnyro** [comment]
I don't ask anyone to use the apps, I'm doing all this voluntary in my free time, and design everything as I like it and as it fits my own needs.
I'll continue maintaining all of the apps, nevertheless you can't expect major design changes because I rather focus on new features or stability improvements instead.

I don't want my projects to become forked for now because that would be a waste of efforts as long as I'm maintaining them too.
However, I'd accept adding an other developer that maintains em together with me, that for it could be considered to move the apps to a different organization.

**Comment by Bnyro** [comment]
If all apps looked the same, development gets boring very fast because you're always seeing the same things.

**Comment by harish-kumaran** [comment]
> If all apps looked the same, development gets boring very fast because you're always seeing the same things.

Okay I get it.
But still... Some UX things u did look very silly to me like adding a pencil icon for adding contacts because it "looks good" and many more.
But I think it's your way of doing stuff maybe I got used to the Google way of doing stuff or maybe not.
But one thing I am sure is this is useless chat that would never end. We can argue Abt these all day yet nothing would change since it's just personal preferences at the end.
So u better do stuff ur way that's the right thing and if I want it to be my way - I shld rather program it not demand u to make it the way I want. You have all rights to do the way you do and ignore my suggestions.
Thanks 👍
