### ISSUE TITLE
Download Photos From Link!

### ISSUE THREAD

**Issue by IzumiSenaSora** [Bnyro/ConnectYou#184]
### Describe your suggested feature

Example:
When i export contacts from google contacts web...
.vcf file will export images links not the actual images... 

Can you add support to download images from that link and store those as a profile photo and show it on contact photos?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share an example VCF file, otherwise I've no idea how to actually handle it...

**Comment by Bnyro** [comment]
Thanks for sharing the VCF file!
Unfortunately I decided against adding support for this for now, because this would require us to add network permissions to the app. In my opinion it's more secure if a contacts app acts offline only, and new users would wonder and worry about the internet permission when installing the app.
