### ISSUE TITLE
Periodic Backup support

### ISSUE THREAD

**Issue by Surendrajat** [Bnyro/ConnectYou#37]
It'll be helpful for automatic sync purpose for someone who doesn't use Google contact sync etc. Implementation will be similar to export, but with one of the two options:

1. Periodic backup (user-defined frequency maybe?, with a max of 5 old backups in backup dir)
2. Backup on change (works fine, Aegis does this)

**Comment by Bnyro** [comment]
This is a very hard task because I don't want to add storage permissions to the app which are required in order to use a directory chosen by the user.
I don't want the app to require permissions that are not essential for the usage/behavior for the app, as in my opinion every app should only use the permissions it really needs.
We could automatically backup it to the app's internal data files, but I doubt that would be any useful.

**Comment by Surendrajat** [comment]
@Bnyro it makes sense, but AFAIK you can access storage using [storage access framework](https://developer.android.com/guide/topics/providers/document-provider) without needing any storage permissions. That way you can let the user choose a dir (local or provided by nextcloud etc.) and use it to save backups.

**Comment by Bnyro** [comment]
That won't persist over app restarts unfortunately.

**Comment by Surendrajat** [comment]
Doesn't this help with persistence?
https://developer.android.com/reference/android/content/Intent#FLAG_GRANT_PERSISTABLE_URI_PERMISSION

**Comment by Bnyro** [comment]
Yes, that could work, however I'm not sure how that would be done without using deprecated code since things work a bit different with Jetpack Compose.

**Comment by Bnyro** [comment]
It's been a bit tricky, but it should work now :)

**Comment by Surendrajat** [comment]
Thanks a lot. Will give a try soon.
