### ISSUE TITLE
Material You Adaptive Icon

### ISSUE THREAD

**Issue by PimpinPumpkin** [Bnyro/ConnectYou#49]
### Describe your suggested feature

A color-adaptive Material You icon would be a great addition to this already amazing app. For example, I've attached a screenshot of what Google Contacts and some other icons look like on my phone.

### Other details

![Screenshot_20230209-112236~2](https://user-images.githubusercontent.com/16398290/217919877-1dca2b9e-09a8-4a6d-8780-4b2cefe2c846.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's very weird actually, are you sure you don't use a third party icon theme like lawnicons?
In theory monochrome icons are supported since the first release of the app, below a screenshot from LineageOS on Android 13:
![Screenshot_20230209-213016_Trebuchet.png](https://user-images.githubusercontent.com/82752168/217939655-c3d209d7-cf0b-40ac-87b8-0ba7e34b003c.png)

**Comment by PimpinPumpkin** [comment]
You're right, I am using Lawnicons. I forgot about that... My bad! Closing this issue.

Thank you so much for this app - it's so simple, yet so polished. I look forward to every new update.
