### ISSUE TITLE
Choose source of contacts

### ISSUE THREAD

**Issue by Sir-Photch** [Bnyro/ConnectYou#57]
### Describe your suggested feature

In Google Contacts, it is possible to choose the location where the contacts are saved.
For example, if you have DaVx5 configured, you can choose your DaVx5-account to save your contacts, or you can choose your local device.

Is this something that could be added? Or is it already present?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not yet present, but it seems a good idea to add support for it. However, it's currently rather something of lower priority.

**Comment by Sir-Photch** [comment]
Looking forward to seeing this implemented, thanks!

**Comment by Bnyro** [comment]
Turns out it would actually be a lot more work than I thought, I supposed DaVx5 would work similar to the normal device contacts and just saved under a different database URI, however I couldn't seem to confirm that.
Since I personally never used it and don't want to invest the time needed, I'm afraid to tell that supporting it is currently not planned, contrary to what I said before.

**Comment by Tobias-Lauerbach** [comment]
I would have also appreciated this feature, but I understand, that it would be to much effort and has no personal use for you.
Is there a way to help you, so it wouldn't be so much effort for you? (without programming skills)

**Comment by Bnyro** [comment]
Does DavX5 show as a separate account type in the filter options? Then it would be possible. (I don't want to set it up only for that)

**Comment by Sir-Photch** [comment]
In google contacts / android-settings -> password and accounts it does.

**Comment by Bnyro** [comment]
And inside CY?

**Comment by Tobias-Lauerbach** [comment]
Yes it does (the name set in DavX5 is also used) here a screenshot of it:

https://nextcloud.lauerbach.de/s/qigFB58LZNCEjgQ

**Comment by Bnyro** [comment]
Oh well, then it's actually possible how I suspected it to be in the beginning, hence re-opening.

**Comment by Sir-Photch** [comment]
> Looking forward to seeing this implemented, thanks!

Apply this again 😃

**Comment by Bnyro** [comment]
Would you also need to "create" additional sources or is it sufficient to choose from existing ones (adding new ones would require the two fields `accountName` and `accountType` to be chosen manually.)

**Comment by Sir-Photch** [comment]
What do you mean by sources in this case? Other accounts in DaVX5? This is already handled by that app.

**Comment by Tobias-Lauerbach** [comment]
> Would you also need to "create" additional sources or is it sufficient to choose from existing ones (adding new ones would require the two fields `accountName` and `accountType` to be chosen manually.)

As far as I understand / would need it, it would sufficient to chose an existing source (adressbook) to store the new contact in.
@Sir-Photch correct me if I am wrong


**Implementation Idea:**
1. Put a similar butten next to the "Manege groups" button, which let's you choose the Contact Source.
2. Put it at the top when edeting/creating the contact like in AOSP, with a drop down of pop up menu.

**1.**
![Screenshot_20230227-172359](https://user-images.githubusercontent.com/62332598/221620819-a72b6f2b-610b-4c3e-8a0e-212d36e82980.png)






**2.**
![Screenshot_20230227-170915](https://user-images.githubusercontent.com/62332598/221616792-4a4cd5af-2d31-4ddd-8f98-00a798600597.png)

**Comment by Sir-Photch** [comment]
Great, looks like I can finally ditch Google Contacts :+1:

**Comment by Bnyro** [comment]
I hope it's working properly since I don't have davx5 set up to test it, feel free to test a debug build from the GitHub actions page!

**Comment by Tobias-Lauerbach** [comment]
In general, it works as far as I have been able to test it. 

Great job! Thanks for the effort you put into this project!

**I encountered some problems:**
1. The selector only shows if there is more than one source already.
2.  If you only have one source, a new contact defaults to "device" as source, even if it's not used (if the only used is DavX5) and can't be changed to something else because of "1".
3. Existing contacts can't be moved from one source to another (this may be a new feature request).

Other improvements:
It would be great to have some visual feedback when selecting a source (e.g. selected source outlined or just a checkbox).


(tested with android 13 and i will try 9 as well)

**Comment by Bnyro** [comment]
For 1. and 2. the solution would be to show it too if there's only one source, right?
3. is a bit harder, for that the contact needs to be deleted first and then a new one needs to created, thus that's currently not possible since it could destroy parts of the contact that are currently not suported (e.g. the organisation).

**Comment by Tobias-Lauerbach** [comment]
1. and 2. Yes, that would be the simplest.
Options could be (as alternatives or extras)
- setting to change the default to a source of your choice
- Default to the used source if only one is selected/exists 

3. That makes sense, I just wasn't sure and thought I'd mention it.
