### ISSUE TITLE
Allow batch functions for copy , move & delete

### ISSUE THREAD

**Issue by kevino-techie** [Bnyro/ConnectYou#60]
### Describe your suggested feature

Currently we have to do functions like copy , move and delete for individual contacts one by one , but it would have been much better if we could **select multiple contacts** at once and perform copy, move and delete functions for all the selected items. 
This would save a lot of time for someone like me who is having more than 400 contacts saved. 
Thanks for making this app 👍

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I agree that this could be a very useful addition, most importantly if you want to move a bunch of contacts from the device to the local in-app contacts database.
I'm still thinking of how we could implement this the most user experience friendly, since currently the long press action shows the single modification options.
Either, we add a "select" option to the dropdown menu containing "move", " copy" and "delete". Or we get completely rid of the single contact actions and select contacts on long pressing which results in the " move", "copy" and "delete" options being shown as a top bar.
I'm interested on input which one others like best, I think the second way would probably be the most user friendly :)
