### ISSUE TITLE
[Discussion] Remaining contact fields to be added

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/ConnectYou#65]
### Describe your suggested feature

This issue is for discussing about which remaining fields that have not yet been added should be added in the future.
There are no plans to support everything possible, the plan is only to support the most important fields, due to two reasons:
1. Efforts and maintainability per field, as each field needs to be implemented for VCards, local contacts and device contacts separately
2. UX: The goal is to keep everything easy to overview and not scare users with lots of available fields when creating a new contact.

The two remaining fields which might be important coming into my mind are the `Organization` field, and the `Website` field. If anyone has other suggestions, or opinions about these two categories, feel free to share your opinion below. Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by dngray** [comment]
My thoughts would be that the app should support the ones that are available in `com.android.contacts`. I'd like to be able to replace that quite old app with this one at some point.

That app has a useful feature, whereby when [`ORG`](https://android.googlesource.com/platform/packages/apps/Contacts.git/+/refs/heads/master/tests/assets/v30_simple.vcf?autodive=0%2F%2F%2F%2F%2F%2F%2F#5) is set it will [show as a company](https://android.googlesource.com/platform/packages/apps/Contacts.git/+/refs/heads/master/src/com/android/contacts/model/Contact.java?autodive=0%2F%2F%2F%2F#312). It is useful to be able to sort companies from contacts at companies. It would also be good if it supported the other items in the [`DataItem.java`](https://android.googlesource.com/platform/packages/apps/Contacts.git/+/refs/heads/master/src/com/android/contacts/model/dataitem/DataItem.java?autodive=0%2F%2F%2F%2F%2F#57) constructor.

**Comment by Bnyro** [comment]
As I already said, I don't plan to add all of these fields for the reasons I mentioned above. Many fields are only used very rarely, thus I personally don't aim to add all of them. 
If anyone wants to take the efforts and create a PR, I'd appreciate it, but I'll limit the remaining ones I'm going to add to two or three, the most important ones, as I personally have never used any that are currently not supported by CY.

**Comment by dngray** [comment]
> If anyone wants to take the efforts and create a PR, I'd appreciate it,

As long as it would be accepted, but yes, I think in general you don't want users to have to have multiple apps managing contacts. Likewise, its not complicating the issue because the ones that are not set simply don't show.

**Comment by dngray** [comment]
Personally I'd just support the ones that `com.android.contacts`, once you've added one, and people can see how that was done, its easy to add others. Another thing to remember is people who use Gmail/Workspace in a business sense often *do* fill in those other fields, otherwise your contacts become a huge mess very quickly.

When you're dealing with a lot of people and you don't want to say their name wrong, the Phonetic name is an excellent one to have.  `ORG` is a non-starter, I wouldn't even use an app that didn't show that. I would implement other fields in [`OrganizationDataItem.java`](https://android.googlesource.com/platform/packages/apps/Contacts.git/+/refs/heads/master/src/com/android/contacts/model/dataitem/OrganizationDataItem.java?autodive=0%2F%2F%2F%2F%2F) too. Department is especially useful in large organizations.

`IM`, is nice if you want to put someone's Matrix ID there or something like that. You can set a [custom protocol](https://android.googlesource.com/platform/packages/apps/Contacts.git/+/refs/heads/master/src/com/android/contacts/model/dataitem/ImDataItem.java?autodive=0%2F%2F%2F%2F%2F#75). `Relation` a lot of old people in my family use because they forget stuff, especially when you know a lot of people, and there's partners and things like that you don't know so well.

**Comment by dngray** [comment]
> outdated stuff (AIM, for crying out loud?!!),

It's really just a generic IM type, with some standard types and a custom one. Just don't implement the standard ones, ICQ, etc, the others are still relevant though.

> the concern here is people moving their contacts over from other apps, in which case we don't want information to be lost by using Connect You.

It shouldn't be, but it just won't be visible.

> Bnyro's point of you about maintainability and the effort it would take to correct implement everything for Connect You's purposes.

it is minimal, effort, once implemented, just implement some of the major ones, and you'll get a PR with the rest.

> I do want to ask: would the effort to support those fields be a one-time thing, or a recurring headache? If it's the latter, it's probably not a good idea.

One time thing.

**Comment by dngray** [comment]
> I decided to approach this differently. Instead of looking at `com.android.contacts`, which is essentially code that has remained mostly untouched for years at this point

It hasn't changed because it doesn't need to, so yeah.

> On a related note regarding UX, I can definitely say that even though the list above may seem like a lot, the way Google Contacts implements these fields looks absolutely sleek and not scary at all (because the more specific stuff isn't visible by default, and doesn't get in the way).

That's pretty much all the ones except [`ImDataItem`](https://android.googlesource.com/platform/packages/apps/Contacts.git/+/refs/heads/master/src/com/android/contacts/model/dataitem/CustomDataItem.java?autodive=0%2F%2F%2F%2F%2F), which is basically the same as "Label (which lets you create a custom label)", they work in basically the same way.

**Comment by Bnyro** [comment]
> @Bnyro How technical would one would have to be to implement these additional fields? I'm fairly certain I wouldn't be able to do it, but I may be mistaken.
>
The UI, the systems contact API and Vcard support are probably very doable since the code is already well structured and adding a field can be done by looking at how it works for the other fields, however what I fear is making database migrations with Room for the in-app contacts.

**Comment by jonaharagon** [comment]
I use the **Organization/Company** field and the **Nickname** field (because it overrides the displayed name in most apps) very extensively in my contacts, and couldn't live without both myself.

I will also add that I use the Company field both in my regular contacts (to remember where I met people) *and* in contacts where _only_ the Company field is set (i.e. no First/Last Name), and in that case I'd expect it to show up as a "business contact" like @dngray mentioned.

**Comment by Tobias-Lauerbach** [comment]
### Label / Groups 
Personally (as mentioned in #59) I would appreciate the `Label` (Contact Groups) field. Because it is a bit more versatile than the `Organization` field because it is better implemented in other services you might sync your contacts with, for example Nextcloud, and it could give you a way to sort your Contacts. You would also be able to give a person multiple Labels, which makes it easier to organize because you don't have to decide for one.
(I know that the sorting would make it more effort to implement, but would make a big usability difference)
What do you think about `Label` vs. `Organization` if you leave aside the need to change all the existing Contacts for switching? @jonaharagon @dngray 
Would that also be an option for your use case?

#### Messenger contacts 
> It's really just a generic IM type, with some standard types and a custom one, which can be whatever the user wants. You could put Telegram name in there or whatever you choose. If you really want just only implement the custom one.
> 

The only other thing I have a use for is the option to add a Messenger ID / “account name” to the appropriate contact. (for example: ThreemaID or Instagram username)
Personally, I don't have an idea or preference for the implementation.
And the 'Label' is much more impotent in my use case, and the messenger ID.
I also think it is something you might just put in the Notes and also be no problem. (which would lower the importance significantly more)

For the Implementation I agree, that more than two or three would clutter the list and then a prioritization is needed which should be shown by default and which in under a “more”-Option while editing.
In the viewing list, I think all information given in the contact should be shown.

**Comment by jonaharagon** [comment]
That doesn't solve at least one use-case (non-person organization contacts). Supporting [standard](https://en.wikipedia.org/wiki/VCard) fields like `ORG` is also important if you are using Connect You as a replacement for the standard contacts app, because other apps (dialers, etc.) already integrate natively with those fields, because vCard has been around for 20+ years.

That being said, labels would still be good; I just don't see it as an either/or situation.

**Comment by dngray** [comment]
> The only other thing I have a use for is the option to add a Messenger ID / “account name” to the appropriate contact. (for example: ThreemaID or Instagram username)

Instagram would be of type "Website" most likely, least that is where I put things like Twitter etc.

But yes the IM type while it had the AIM type, it also had a "custom" which is basically insert whatever you want and then the ID. I'm pretty sure Threema has a numerical number.

**Comment by Tobias-Lauerbach** [comment]
> Instagram would be of type "Website" most likely, least that is where I put things like Twitter etc.
> 
Yes with web based usernames that would work


> But yes the IM type while it had the AIM type, it also had a "custom" which is basically insert whatever you want and then the ID. I'm pretty sure Threema has a numerical number.

Threema has an ID which has a combination of letters and numbers.
As I sad I have no real technical knowledge of the IM Type and it was just an example for a way to implement it, it is possible that there are better ways, and I also would be OK with it, if I just need to write it in the notes section. I just wanted pick two out of the list which @matchboxbananasynergy  has posted so it would may be easier to prioritize some types to make is less work to implement.

**Comment by Tobias-Lauerbach** [comment]
> That doesn't solve at least one use-case (non-person organization contacts).

I am not shure what you mean with the "non-person organization contacts" could you please explain it and where the problem with using labels for would be?


> Supporting [standard](https://en.wikipedia.org/wiki/VCard) fields like `ORG` is also important if you are using Connect You as a replacement for the standard contacts app, because other apps (dialers, etc.) already integrate natively with those fields, because vCard has been around for 20+ years.

Sorry for asking again, but which kind of Support do you mean? (like showing the company name in the dialer or something else?)

(lables/ groups have also been around for a while, as far as I know)

> That being said, labels would still be good; I just don't see it as an either/or situation.

I agree partly because @Bnyro ment he would prefer to only implement two or three, so it would be possible that there is the need to decide...

**Comment by Bnyro** [comment]
> What happens when someone imports a VCF file that _does_ include the missing properties though? Does that information just not populate? I would personally still advocate for feature parity with Google's contacts app, but we definitely have progress here :)
>
Unsupported information is currently not being imported and thus lost when exporting the imported contacts. Your previously mentioned solution to move everything into the notes field might be an idea for the future, however as far as I know Vcards don't support the `IM` field anyways, not sure about the relations field though.
